### ISSUE TITLE
question 

### ISSUE THREAD

**Issue by abodinagdat16** [RohitKushvaha01/Proot#1]
proot its not working on Android 14 😬 idk why ...

**Comment by RohitKushvaha01** [comment]
> proot its not working on Android 14 😬 idk why ...

@abodinagdat16 send screenshots/error

**Comment by RohitKushvaha01** [comment]
> ![Messenger_creation_E1563403-63A2-40FA-A74D-00D615B0EAB3](https://private-user-images.githubusercontent.com/69758268/365577867-0288a476-3eef-431f-9b9e-1374f360c190.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU4NzE5MjQsIm5iZiI6MTcyNTg3MTYyNCwicGF0aCI6Ii82OTc1ODI2OC8zNjU1Nzc4NjctMDI4OGE0NzYtM2VlZi00MzFmLTliOWUtMTM3NGYzNjBjMTkwLmpwZWc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwOVQwODQ3MDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yNWI3ZWRjYTcwNGQ0MDYxYWI0ZjdjOGJhMmZhOWRkOGVkOTkxM2NhNTMyMDdmN2I5MDE2OTc1NzM4OGExZjUyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.8xK_2CQY7tZ8vr0E7Dr1MYsKJ1sfoOE5-KE5Ad4o7Ro)

this proot is compiled for the com.rk.xededitor package (Karbon). It will not function with any other package name. To adapt it for your use, you must modify the GNUmakefile by replacing com.rk.xededitor with your application's package name. Additionally, you need to configure the LD_LIBRARY_PATH environment variable to point to the libtalloc library.
